'''title'''
__title__ = 'cpgames'
'''description'''
__description__ = 'Games: Create interesting games in pure python'
'''url'''
__url__ = 'https://github.com/dannz510/PYTHON-GAME-MASTER'
'''version'''
__version__ = '0.1.3'
'''author'''
__author__ = 'Dannz'
'''email'''
__email__ = 'mini51019158@gmail.com'
'''license'''
__license__ = 'Apache License 2.0'
'''copyright'''
__copyright__ = 'Copyright 2025 - 2026 Dannz'